site_name: Hashipcorp Terraform Associate Study Guide
theme:
  name: material
  palette: 
    scheme: slate # Dark mode is usually better for code
  features:
    - content.code.copy
    - navigation.prune

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

docs_dir: content 
site_dir: docs
site_url: https://rcoupland91.github.io/azure-terraform-associate-study/
use_directory_urls: true